export const PROGRAM_CATEGORIES: Record<string, string> = {
  // Engineering
  "btech-artificial-intelligence": "Engineering",
  "btech-ai": "Engineering",
  "btech-civil-engineering": "Engineering",
  "btech-civil": "Engineering",
  "btech-computer-science-engineering": "Engineering",
  "btech-cse": "Engineering",
  "btech-electrical-engineering": "Engineering",
  "btech-ee": "Engineering",
  "btech-electronics-communication-engineering": "Engineering",
  "btech-ece": "Engineering",
  "btech-mechanical-engineering": "Engineering",
  "btech-me": "Engineering",
  "mtech-civil-engineering": "Engineering",
  "mtech-civil": "Engineering",
  "mtech-computer-science-engineering": "Engineering",
  "mtech-cse": "Engineering",
  "mtech-electronics-communication-engineering": "Engineering",
  "mtech-ee": "Engineering",
  "mtech-mechanical-engineering": "Engineering",
  // Diploma Engineering
  "diploma-in-civil-engineering": "Diploma",
  "diploma-civil": "Diploma",
  "diploma-in-electrical-engineering": "Diploma",
  "diploma-ee": "Diploma",
  "diploma-in-mechanical-engineering": "Diploma",
  "diploma-me": "Diploma",
  "diploma-cse": "Diploma",
  "diploma-computer-science-engineering": "Diploma",
  "diploma-in-computer-science-engineering": "Diploma",
  // Pharmacy
  "bpharmacy": "Pharmacy",
  "bpharm": "Pharmacy",
  "mpharmacy-pharmaceutics": "Pharmacy",
  "mpharmaceutics": "Pharmacy",
  "mpharmacy-pharmacology": "Pharmacy",
  "mpharmacology": "Pharmacy",
  "mpharm": "Pharmacy",
  "pharmad": "Pharmacy",
  "pharmd": "Pharmacy",
  "dpharm": "Pharmacy",
  "diploma-in-pharmacy": "Pharmacy",
  // Medical Sciences & Allied Health
  "bsc-hons-anesthesia-technology": "Medical Sciences & Allied Health",
  "bsc-hons-medical-lab-science": "Medical Sciences & Allied Health",
  "bsc-hons-optometry": "Medical Sciences & Allied Health",
  "bsc-hons-radio-medical-imaging-technology": "Medical Sciences & Allied Health",
  "bsc-cardiac-care-technology": "Medical Sciences & Allied Health",
  "bsc-hons-operation-theatre-technology": "Medical Sciences & Allied Health",
  "bsc-radiology-imaging-technology": "Medical Sciences & Allied Health",
  "bsc-medical-lab-sciences": "Medical Sciences & Allied Health",
  "bsc-medical-lab-sciences-svftm": "Medical Sciences & Allied Health",
  "bsc-operation-theatre-technology-svftm": "Medical Sciences & Allied Health",
  "bsc-radiology-svftm": "Medical Sciences & Allied Health",
  "msc-medical-microbiology": "Medical Sciences & Allied Health",
  "msc-radiology-and-imaging-technology": "Medical Sciences & Allied Health",
  "msc-anesthesia-operation-theater-technology": "Medical Sciences & Allied Health",
  "msc-cardiac-care": "Medical Sciences & Allied Health",
  "msc-cardiac-care-technology": "Medical Sciences & Allied Health",
  "msc-medical-lab-science-clinical-biochemistry": "Medical Sciences & Allied Health",
  "bachelor-of-physiotherapy": "Medical Sciences & Allied Health",
  "bachelor-in-hospital-administration": "Medical Sciences & Allied Health",
  "diploma-in-medical-lab-technology": "Medical Sciences & Allied Health",
  "dmlt": "Medical Sciences & Allied Health",
  "diploma-in-nursing-assistant": "Medical Sciences & Allied Health",
  // Computer Applications & IT
  "bachelor-of-computer-applications": "Computer Applications",
  "bachelor-of-computer-applications-svcmt": "Computer Applications",
  "bachelor-of-computer-applications-svftm": "Computer Applications",
  "bachelor-in-computer-application": "Computer Applications",
  "bca": "Computer Applications",
  "master-of-computer-applications": "Computer Applications",
  "masters-in-computer-applications": "Computer Applications",
  "mca": "Computer Applications",
  "bsc-information-technology": "Computer Applications",
  "bsc-it": "Computer Applications",
  "post-graduate-diploma-in-computer-application": "Computer Applications",
  "pgdca": "Computer Applications",
  "bachelor-of-arts-computer-science": "Arts & Education",
  // Management
  "master-of-business-administration": "Management",
  "masters-in-business-administration": "Management",
  "mba": "Management",
  "bachelor-of-business-administration": "Management",
  "bachelor-of-business-administration-svcmt": "Management",
  "bachelor-of-business-administration-svftm": "Management",
  "bachelor-in-business-administration": "Management",
  "bba": "Management",
  // Commerce
  "bachelor-of-commerce": "Commerce",
  "bcom": "Commerce",
  "bachelor-of-commerce-h": "Commerce",
  "master-of-commerce": "Commerce",
  "masters-of-commerce": "Commerce",
  // Education & Arts
  "bachelor-in-education": "Arts & Education",
  "bed": "Arts & Education",
  "masters-in-education": "Arts & Education",
  "med": "Arts & Education",
  "ma-education": "Arts & Education",
  "bachelor-of-arts": "Arts & Education",
  "education-arts": "Arts & Education",
  "ba": "Arts & Education",
  "ba-journalism-and-mass-communication": "Arts & Education",
  // Law
  "llb": "Law",
  "ba-llb": "Law",
  // Hotel Management
  "bachelor-of-hotel-management-catering-technology": "Hotel Management",
  "master-of-hotel-management-catering-technology": "Hotel Management",
  "mhmct": "Hotel Management",
  "bvoc-hotel-management-catering": "Hotel Management",
  "bvoc-hospitality": "Hotel Management",
  "catering-hospitality": "Hotel Management",
  "bsc-hm": "Hotel Management",
  "bsc-honors-in-nutrition-and-dietetics": "Hotel Management",
  // Science
  "bsc-non-medical": "Science",
  "msc-chemistry": "Science",
  "msc-math": "Science",
  "msc-mathematics": "Science",
  "msc-physics": "Science",
  // Vocational / ITI
  "copa": "Vocational & ITI",
  "plumber": "Vocational & ITI",
  "welderge": "Vocational & ITI",
  "welder-ge": "Vocational & ITI",
};

export const PROGRAM_TAGLINES: Record<string, string> = {
  // B.Tech
  "btech-artificial-intelligence":               "WHERE ALGORITHMS MEET AMBITION",
  "btech-ai":                                    "WHERE ALGORITHMS MEET AMBITION",
  "btech-civil-engineering":                     "TURNING BLUEPRINTS INTO SKYLINES",
  "btech-civil":                                 "TURNING BLUEPRINTS INTO SKYLINES",
  "btech-computer-science-engineering":          "PROGRAMMING FOR FUTURE, TODAY",
  "btech-cse":                                   "PROGRAMMING FOR FUTURE, TODAY",
  "btech-electrical-engineering":                "ENERGISING TOMORROW'S INFRASTRUCTURE",
  "btech-ee":                                    "ENERGISING TOMORROW'S INFRASTRUCTURE",
  "btech-electronics-communication-engineering": "CONNECTING THE WORLD, ONE CIRCUIT AT A TIME",
  "btech-ece":                                   "CONNECTING THE WORLD, ONE CIRCUIT AT A TIME",
  "btech-mechanical-engineering":                "WHERE PRECISION MEETS INNOVATION",
  "btech-me":                                    "WHERE PRECISION MEETS INNOVATION",
  // M.Tech
  "mtech-civil-engineering":                     "ENGINEERING TOMORROW'S LANDMARKS",
  "mtech-civil":                                 "ENGINEERING TOMORROW'S LANDMARKS",
  "mtech-computer-science-engineering":          "IGNITE INNOVATION AND RESEARCH",
  "mtech-cse":                                   "IGNITE INNOVATION AND RESEARCH",
  "mtech-electronics-communication-engineering": "PUSHING THE BOUNDARIES OF SIGNAL & SYSTEMS",
  "mtech-ee":                                    "HIGH VOLTAGE EXPERTISE FOR A SUSTAINABLE GRID",
  "mtech-mechanical-engineering":                "FROM DESIGN TO DEPLOYMENT — PRECISION REDEFINED",
  // Pharmacy
  "bpharmacy":                                   "WHERE CHEMISTRY MEETS COMPASSIONATE CARE",
  "bpharm":                                      "WHERE CHEMISTRY MEETS COMPASSIONATE CARE",
  "mpharmacy-pharmaceutics":                     "FORMULATING THE MEDICINES OF TOMORROW",
  "mpharmaceutics":                              "FORMULATING THE MEDICINES OF TOMORROW",
  "mpharmacy-pharmacology":                      "DECODING HOW DRUGS HEAL",
  "mpharmacology":                               "DECODING HOW DRUGS HEAL",
  "mpharm":                                      "THE SCIENCE BEHIND EVERY CURE",
  "pharmad":                                     "SIX YEARS THAT REDEFINE PHARMACY PRACTICE",
  "pharmd":                                      "SIX YEARS THAT REDEFINE PHARMACY PRACTICE",
  "dpharm":                                      "YOUR FIRST STEP INTO PHARMACEUTICAL CARE",
  "diploma-in-pharmacy":                         "YOUR FIRST STEP INTO PHARMACEUTICAL CARE",
  // Medical Sciences & Allied Health
  "bsc-hons-anesthesia-technology":              "THE SILENT HEROES OF EVERY OPERATION",
  "bsc-hons-medical-lab-science":                "DIAGNOSE, DETECT, DELIVER ANSWERS",
  "bsc-hons-optometry":                          "BRINGING THE WORLD INTO FOCUS",
  "bsc-hons-radio-medical-imaging-technology":   "SEE BEYOND THE SURFACE",
  "bsc-cardiac-care-technology":                 "EVERY HEARTBEAT MATTERS",
  "bsc-hons-operation-theatre-technology":       "WHERE PRECISION SAVES LIVES",
  "bsc-radiology-imaging-technology":            "IMAGING WHAT EYES CANNOT SEE",
  "bsc-medical-lab-sciences":                    "DIAGNOSE, DETECT, DELIVER ANSWERS",
  "bsc-medical-lab-sciences-svftm":              "DIAGNOSE, DETECT, DELIVER ANSWERS",
  "bsc-operation-theatre-technology-svftm":      "WHERE PRECISION SAVES LIVES",
  "bsc-radiology-svftm":                         "IMAGING WHAT EYES CANNOT SEE",
  "bsc-non-medical":                             "BUILDING FOUNDATIONS IN SCIENCE, INNOVATION, AND DISCOVERY",
  "msc-medical-microbiology":                    "HUNTING PATHOGENS, PROTECTING LIVES",
  "msc-radiology-and-imaging-technology":        "A DEEPER LOOK AT HUMAN HEALTH",
  "msc-anesthesia-operation-theater-technology": "THE SCIENCE OF SAFE, PAINLESS SURGERY",
  "msc-cardiac-care":                            "LEADING THE CHARGE IN HEART HEALTH",
  "msc-cardiac-care-technology":                 "LEADING THE CHARGE IN HEART HEALTH",
  "msc-medical-lab-science-clinical-biochemistry": "BIOCHEMISTRY AT THE FRONTLINE OF DIAGNOSTICS",
  "bachelor-of-physiotherapy":                   "RESTORE MOVEMENT, RESTORE LIVES",
  "bachelor-in-hospital-administration":         "RUN THE HOSPITAL. SHAPE HEALTHCARE.",
  "diploma-in-medical-lab-technology":           "WHERE LAB SKILLS SAVE LIVES",
  "dmlt":                                        "WHERE LAB SKILLS SAVE LIVES",
  "diploma-in-nursing-assistant":                "CARE, COMFORT AND CLINICAL SKILL",
  // Computer Applications & IT
  "bachelor-of-computer-applications":           "CODE YOUR CAREER FROM DAY ONE",
  "bachelor-of-computer-applications-svcmt":     "CODE YOUR CAREER FROM DAY ONE",
  "bachelor-of-computer-applications-svftm":     "CODE YOUR CAREER FROM DAY ONE",
  "bachelor-in-computer-application":            "CODE YOUR CAREER FROM DAY ONE",
  "bca":                                         "CODE YOUR CAREER FROM DAY ONE",
  "master-of-computer-applications":             "THINK BIGGER. CODE SMARTER. LEAD TECH.",
  "masters-in-computer-applications":            "THINK BIGGER. CODE SMARTER. LEAD TECH.",
  "mca":                                         "THINK BIGGER. CODE SMARTER. LEAD TECH.",
  "bsc-information-technology":                  "TECHNOLOGY IS THE LANGUAGE — SPEAK IT FLUENTLY",
  "bsc-it":                                      "TECHNOLOGY IS THE LANGUAGE — SPEAK IT FLUENTLY",
  "post-graduate-diploma-in-computer-application": "FAST-TRACK YOUR TECH CAREER",
  "pgdca":                                       "FAST-TRACK YOUR TECH CAREER",
  "bachelor-of-arts-computer-science":           "WHERE HUMANITIES MEET THE DIGITAL AGE",
  // Management
  "master-of-business-administration":           "LEAD WITH STRATEGY. GROW WITH PURPOSE.",
  "masters-in-business-administration":          "LEAD WITH STRATEGY. GROW WITH PURPOSE.",
  "mba":                                         "LEAD WITH STRATEGY. GROW WITH PURPOSE.",
  "bachelor-of-business-administration":         "TOMORROW'S LEADERS START HERE",
  "bachelor-of-business-administration-svcmt":   "TOMORROW'S LEADERS START HERE",
  "bachelor-of-business-administration-svftm":   "TOMORROW'S LEADERS START HERE",
  "bachelor-in-business-administration":         "TOMORROW'S LEADERS START HERE",
  "bba":                                         "TOMORROW'S LEADERS START HERE",
  // Commerce
  "bachelor-of-commerce":                        "NUMBERS THAT TELL A STORY",
  "bcom":                                        "NUMBERS THAT TELL A STORY",
  "bachelor-of-commerce-h":                      "NUMBERS THAT TELL A STORY",
  "master-of-commerce":                          "DEEP EXPERTISE IN FINANCE & ACCOUNTING",
  "masters-of-commerce":                         "DEEP EXPERTISE IN FINANCE & ACCOUNTING",
  // Education
  "bachelor-in-education":                       "INSPIRE A GENERATION",
  "bed":                                         "INSPIRE A GENERATION",
  "masters-in-education":                        "TEACH DEEPER. LEAD FURTHER.",
  "med":                                         "TEACH DEEPER. LEAD FURTHER.",
  "ma-education":                                "REIMAGINING HOW THE WORLD LEARNS",
  // Arts
  "bachelor-of-arts":                            "THINK CRITICALLY. WRITE POWERFULLY. LEAD CHANGE.",
  "education-arts":                              "THINK CRITICALLY. WRITE POWERFULLY. LEAD CHANGE.",
  "ba":                                          "THINK CRITICALLY. WRITE POWERFULLY. LEAD CHANGE.",
  "ba-journalism-and-mass-communication":        "STORIES THAT SHAPE THE WORLD",
  // Law
  "llb":                                         "WHERE JUSTICE MEETS JURISPRUDENCE",
  "ba-llb":                                      "LAW WITH A LIBERAL LENS",
  // Hotel Management
  "bachelor-of-hotel-management-catering-technology": "HOSPITALITY IS AN ART. WE MAKE IT A CAREER.",
  "master-of-hotel-management-catering-technology":   "THE BUSINESS OF EXTRAORDINARY EXPERIENCES",
  "mhmct":                                       "THE BUSINESS OF EXTRAORDINARY EXPERIENCES",
  "bvoc-hotel-management-catering":              "SKILLS FIRST. INDUSTRY READY.",
  "bvoc-hospitality":                            "SKILLS FIRST. INDUSTRY READY.",
  "catering-hospitality":                        "FROM THE KITCHEN TO THE BOARDROOM",
  "bsc-hm":                                      "NOURISHMENT, WELLNESS & THE SCIENCE OF FOOD",
  "bsc-honors-in-nutrition-and-dietetics":       "FOOD AS MEDICINE. SCIENCE AS YOUR GUIDE.",
  // Diploma Engineering
  "diploma-in-civil-engineering":                "LAY THE GROUNDWORK FOR YOUR FUTURE",
  "diploma-civil":                               "LAY THE GROUNDWORK FOR YOUR FUTURE",
  "diploma-in-electrical-engineering":           "SPARK YOUR ENGINEERING CAREER",
  "diploma-ee":                                  "SPARK YOUR ENGINEERING CAREER",
  "diploma-in-mechanical-engineering":           "HANDS ON. CAREER READY.",
  "diploma-me":                                  "HANDS ON. CAREER READY.",
  "diploma-cse":                                 "FROM CODE TO CAREER IN THREE YEARS",
  "diploma-computer-science-engineering":        "FROM CODE TO CAREER IN THREE YEARS",
  "diploma-in-computer-science-engineering":     "FROM CODE TO CAREER IN THREE YEARS",
  // Science
  "msc-chemistry":                               "REACTIONS THAT CHANGE THE WORLD",
  "msc-math":                                    "THE LANGUAGE THAT RUNS THE UNIVERSE",
  "msc-mathematics":                             "THE LANGUAGE THAT RUNS THE UNIVERSE",
  "msc-physics":                                 "FROM QUARKS TO COSMOS",
  // Vocational / ITI
  "copa":                                        "OFFICE SKILLS FOR THE DIGITAL ECONOMY",
  "plumber":                                     "ESSENTIAL SKILLS. ESSENTIAL TRADE.",
  "welderge":                                    "WHERE FIRE AND SKILL FORGE A CAREER",
  "welder-ge":                                   "WHERE FIRE AND SKILL FORGE A CAREER",
};
